version: '3.9'

services:
  frontend-mock:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    networks:
      - alphapulse-network
    container_name: alphapulse-frontend-mock
    depends_on:
      - fastapi

  fastapi:
    external: true
    name: alphapulse-fastapi

networks:
  alphapulse-network:
    external: true
    name: alphapulse-network