apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alphapulse

resources:
  - namespace.yaml
  - storage.yaml
  - postgres.yaml
  - fastapi.yaml
  - frontend.yaml
  - airflow.yaml
  - mlflow.yaml
  - trainer.yaml
