apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alphapulse

resources:
  - namespace.yaml
  - storage.yaml
  - postgres.yaml
  - fastapi.yaml
  - frontend.yaml
  - airflow.yaml
  - mlflow.yaml
  - mlflow-middleware.yaml
  - fastapi-middleware.yaml
  - trainer.yaml
  - grafana.yaml

configMapGenerator:
  - name: postgres-init-scripts
    files:
      - init-databases.sh=scripts/init-databases.sh
      - init-db.sql=scripts/init-db.sql
